services:
  tnvclothingid:
    build: .
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tnvclothingid.entrypoints=https'
      - 'traefik.http.routers.tnvclothingid.rule=Host(`tnvclothing.id`)'
      - 'traefik.http.routers.tnvclothingid.tls=true'
      - 'traefik.http.services.tnvclothingid.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
